// Code generated by MockGen. DO NOT EDIT.
// Source: backlog_repository.go
//
// Generated by this command:
//
//      mockgen -source=backlog_repository.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
        context "context"
        reflect "reflect"
        time "time"

        models "github.com/boskuv/goreminder/internal/models"
        gomock "go.uber.org/mock/gomock"
)

// MockBacklogRepository is a mock of BacklogRepository interface.
type MockBacklogRepository struct {
        ctrl     *gomock.Controller
        recorder *MockBacklogRepositoryMockRecorder
        isgomock struct{}
}

// MockBacklogRepositoryMockRecorder is the mock recorder for MockBacklogRepository.
type MockBacklogRepositoryMockRecorder struct {
        mock *MockBacklogRepository
}

// NewMockBacklogRepository creates a new mock instance.
func NewMockBacklogRepository(ctrl *gomock.Controller) *MockBacklogRepository {
        mock := &MockBacklogRepository{ctrl: ctrl}
        mock.recorder = &MockBacklogRepositoryMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBacklogRepository) EXPECT() *MockBacklogRepositoryMockRecorder {
        return m.recorder
}

// CreateBacklog mocks base method.
func (m *MockBacklogRepository) CreateBacklog(ctx context.Context, backlog *models.Backlog) (int64, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "CreateBacklog", ctx, backlog)
        ret0, _ := ret[0].(int64)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// CreateBacklog indicates an expected call of CreateBacklog.
func (mr *MockBacklogRepositoryMockRecorder) CreateBacklog(ctx, backlog any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBacklog", reflect.TypeOf((*MockBacklogRepository)(nil).CreateBacklog), ctx, backlog)
}

// DeleteBacklog mocks base method.
func (m *MockBacklogRepository) DeleteBacklog(ctx context.Context, id int64) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "DeleteBacklog", ctx, id)
        ret0, _ := ret[0].(error)
        return ret0
}

// DeleteBacklog indicates an expected call of DeleteBacklog.
func (mr *MockBacklogRepositoryMockRecorder) DeleteBacklog(ctx, id any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBacklog", reflect.TypeOf((*MockBacklogRepository)(nil).DeleteBacklog), ctx, id)
}

// GetAllBacklogs mocks base method.
func (m *MockBacklogRepository) GetAllBacklogs(ctx context.Context, page, pageSize int, orderBy string, userID *int64, completed *bool) ([]*models.Backlog, int, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetAllBacklogs", ctx, page, pageSize, orderBy, userID, completed)
        ret0, _ := ret[0].([]*models.Backlog)
        ret1, _ := ret[1].(int)
        ret2, _ := ret[2].(error)
        return ret0, ret1, ret2
}

// GetAllBacklogs indicates an expected call of GetAllBacklogs.
func (mr *MockBacklogRepositoryMockRecorder) GetAllBacklogs(ctx, page, pageSize, orderBy, userID, completed any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBacklogs", reflect.TypeOf((*MockBacklogRepository)(nil).GetAllBacklogs), ctx, page, pageSize, orderBy, userID, completed)
}

// GetBacklogByID mocks base method.
func (m *MockBacklogRepository) GetBacklogByID(ctx context.Context, id int64) (*models.Backlog, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetBacklogByID", ctx, id)
        ret0, _ := ret[0].(*models.Backlog)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetBacklogByID indicates an expected call of GetBacklogByID.
func (mr *MockBacklogRepositoryMockRecorder) GetBacklogByID(ctx, id any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBacklogByID", reflect.TypeOf((*MockBacklogRepository)(nil).GetBacklogByID), ctx, id)
}

// GetCompletedBacklogsCount mocks base method.
func (m *MockBacklogRepository) GetCompletedBacklogsCount(ctx context.Context, userID int64, startDate, endDate time.Time) (int, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetCompletedBacklogsCount", ctx, userID, startDate, endDate)
        ret0, _ := ret[0].(int)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetCompletedBacklogsCount indicates an expected call of GetCompletedBacklogsCount.
func (mr *MockBacklogRepositoryMockRecorder) GetCompletedBacklogsCount(ctx, userID, startDate, endDate any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompletedBacklogsCount", reflect.TypeOf((*MockBacklogRepository)(nil).GetCompletedBacklogsCount), ctx, userID, startDate, endDate)
}

// UpdateBacklog mocks base method.
func (m *MockBacklogRepository) UpdateBacklog(ctx context.Context, backlog *models.Backlog) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "UpdateBacklog", ctx, backlog)
        ret0, _ := ret[0].(error)
        return ret0
}

// UpdateBacklog indicates an expected call of UpdateBacklog.
func (mr *MockBacklogRepositoryMockRecorder) UpdateBacklog(ctx, backlog any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBacklog", reflect.TypeOf((*MockBacklogRepository)(nil).UpdateBacklog), ctx, backlog)
}