// Code generated by MockGen. DO NOT EDIT.
// Source: digest_settings_repository.go
//
// Generated by this command:
//
//      mockgen -source=digest_settings_repository.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
        context "context"
        reflect "reflect"

        models "github.com/boskuv/goreminder/internal/models"
        gomock "go.uber.org/mock/gomock"
)

// MockDigestSettingsRepository is a mock of DigestSettingsRepository interface.
type MockDigestSettingsRepository struct {
        ctrl     *gomock.Controller
        recorder *MockDigestSettingsRepositoryMockRecorder
        isgomock struct{}
}

// MockDigestSettingsRepositoryMockRecorder is the mock recorder for MockDigestSettingsRepository.
type MockDigestSettingsRepositoryMockRecorder struct {
        mock *MockDigestSettingsRepository
}

// NewMockDigestSettingsRepository creates a new mock instance.
func NewMockDigestSettingsRepository(ctrl *gomock.Controller) *MockDigestSettingsRepository {
        mock := &MockDigestSettingsRepository{ctrl: ctrl}
        mock.recorder = &MockDigestSettingsRepositoryMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDigestSettingsRepository) EXPECT() *MockDigestSettingsRepositoryMockRecorder {
        return m.recorder
}

// CreateDigestSettings mocks base method.
func (m *MockDigestSettingsRepository) CreateDigestSettings(ctx context.Context, settings *models.DigestSettings) (int64, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "CreateDigestSettings", ctx, settings)
        ret0, _ := ret[0].(int64)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// CreateDigestSettings indicates an expected call of CreateDigestSettings.
func (mr *MockDigestSettingsRepositoryMockRecorder) CreateDigestSettings(ctx, settings any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDigestSettings", reflect.TypeOf((*MockDigestSettingsRepository)(nil).CreateDigestSettings), ctx, settings)
}

// DeleteDigestSettings mocks base method.
func (m *MockDigestSettingsRepository) DeleteDigestSettings(ctx context.Context, userID int64, messengerRelatedUserID *int) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "DeleteDigestSettings", ctx, userID, messengerRelatedUserID)
        ret0, _ := ret[0].(error)
        return ret0
}

// DeleteDigestSettings indicates an expected call of DeleteDigestSettings.
func (mr *MockDigestSettingsRepositoryMockRecorder) DeleteDigestSettings(ctx, userID, messengerRelatedUserID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDigestSettings", reflect.TypeOf((*MockDigestSettingsRepository)(nil).DeleteDigestSettings), ctx, userID, messengerRelatedUserID)
}

// GetAllDigestSettings mocks base method.
func (m *MockDigestSettingsRepository) GetAllDigestSettings(ctx context.Context, page, pageSize int, orderBy string, userID *int64) ([]*models.DigestSettings, int, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetAllDigestSettings", ctx, page, pageSize, orderBy, userID)
        ret0, _ := ret[0].([]*models.DigestSettings)
        ret1, _ := ret[1].(int)
        ret2, _ := ret[2].(error)
        return ret0, ret1, ret2
}

// GetAllDigestSettings indicates an expected call of GetAllDigestSettings.
func (mr *MockDigestSettingsRepositoryMockRecorder) GetAllDigestSettings(ctx, page, pageSize, orderBy, userID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDigestSettings", reflect.TypeOf((*MockDigestSettingsRepository)(nil).GetAllDigestSettings), ctx, page, pageSize, orderBy, userID)
}

// GetDigestSettingsByID mocks base method.
func (m *MockDigestSettingsRepository) GetDigestSettingsByID(ctx context.Context, id int64) (*models.DigestSettings, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetDigestSettingsByID", ctx, id)
        ret0, _ := ret[0].(*models.DigestSettings)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetDigestSettingsByID indicates an expected call of GetDigestSettingsByID.
func (mr *MockDigestSettingsRepositoryMockRecorder) GetDigestSettingsByID(ctx, id any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDigestSettingsByID", reflect.TypeOf((*MockDigestSettingsRepository)(nil).GetDigestSettingsByID), ctx, id)
}

// GetDigestSettingsByUserID mocks base method.
func (m *MockDigestSettingsRepository) GetDigestSettingsByUserID(ctx context.Context, userID int64, messengerRelatedUserID *int) (*models.DigestSettings, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetDigestSettingsByUserID", ctx, userID, messengerRelatedUserID)
        ret0, _ := ret[0].(*models.DigestSettings)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetDigestSettingsByUserID indicates an expected call of GetDigestSettingsByUserID.
func (mr *MockDigestSettingsRepositoryMockRecorder) GetDigestSettingsByUserID(ctx, userID, messengerRelatedUserID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDigestSettingsByUserID", reflect.TypeOf((*MockDigestSettingsRepository)(nil).GetDigestSettingsByUserID), ctx, userID, messengerRelatedUserID)
}

// UpdateDigestSettings mocks base method.
func (m *MockDigestSettingsRepository) UpdateDigestSettings(ctx context.Context, settings *models.DigestSettings) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "UpdateDigestSettings", ctx, settings)
        ret0, _ := ret[0].(error)
        return ret0
}

// UpdateDigestSettings indicates an expected call of UpdateDigestSettings.
func (mr *MockDigestSettingsRepositoryMockRecorder) UpdateDigestSettings(ctx, settings any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDigestSettings", reflect.TypeOf((*MockDigestSettingsRepository)(nil).UpdateDigestSettings), ctx, settings)
}