// Code generated by MockGen. DO NOT EDIT.
// Source: messenger_repository.go
//
// Generated by this command:
//
//      mockgen -source=messenger_repository.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
        context "context"
        reflect "reflect"

        models "github.com/boskuv/goreminder/internal/models"
        gomock "go.uber.org/mock/gomock"
)

// MockMessengerRepository is a mock of MessengerRepository interface.
type MockMessengerRepository struct {
        ctrl     *gomock.Controller
        recorder *MockMessengerRepositoryMockRecorder
        isgomock struct{}
}

// MockMessengerRepositoryMockRecorder is the mock recorder for MockMessengerRepository.
type MockMessengerRepositoryMockRecorder struct {
        mock *MockMessengerRepository
}

// NewMockMessengerRepository creates a new mock instance.
func NewMockMessengerRepository(ctrl *gomock.Controller) *MockMessengerRepository {
        mock := &MockMessengerRepository{ctrl: ctrl}
        mock.recorder = &MockMessengerRepositoryMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessengerRepository) EXPECT() *MockMessengerRepositoryMockRecorder {
        return m.recorder
}

// CreateMessenger mocks base method.
func (m *MockMessengerRepository) CreateMessenger(ctx context.Context, messenger *models.Messenger) (int64, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "CreateMessenger", ctx, messenger)
        ret0, _ := ret[0].(int64)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// CreateMessenger indicates an expected call of CreateMessenger.
func (mr *MockMessengerRepositoryMockRecorder) CreateMessenger(ctx, messenger any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessenger", reflect.TypeOf((*MockMessengerRepository)(nil).CreateMessenger), ctx, messenger)
}

// CreateMessengerRelatedUser mocks base method.
func (m *MockMessengerRepository) CreateMessengerRelatedUser(ctx context.Context, messengerRelatedUser *models.MessengerRelatedUser) (int64, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "CreateMessengerRelatedUser", ctx, messengerRelatedUser)
        ret0, _ := ret[0].(int64)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// CreateMessengerRelatedUser indicates an expected call of CreateMessengerRelatedUser.
func (mr *MockMessengerRepositoryMockRecorder) CreateMessengerRelatedUser(ctx, messengerRelatedUser any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessengerRelatedUser", reflect.TypeOf((*MockMessengerRepository)(nil).CreateMessengerRelatedUser), ctx, messengerRelatedUser)
}

// DeleteMessengerRelatedUserByUserID mocks base method.
func (m *MockMessengerRepository) DeleteMessengerRelatedUserByUserID(ctx context.Context, userID int64) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "DeleteMessengerRelatedUserByUserID", ctx, userID)
        ret0, _ := ret[0].(error)
        return ret0
}

// DeleteMessengerRelatedUserByUserID indicates an expected call of DeleteMessengerRelatedUserByUserID.
func (mr *MockMessengerRepositoryMockRecorder) DeleteMessengerRelatedUserByUserID(ctx, userID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessengerRelatedUserByUserID", reflect.TypeOf((*MockMessengerRepository)(nil).DeleteMessengerRelatedUserByUserID), ctx, userID)
}

// GetAllMessengerRelatedUsers mocks base method.
func (m *MockMessengerRepository) GetAllMessengerRelatedUsers(ctx context.Context, page, pageSize int, orderBy string) ([]*models.MessengerRelatedUser, int, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetAllMessengerRelatedUsers", ctx, page, pageSize, orderBy)
        ret0, _ := ret[0].([]*models.MessengerRelatedUser)
        ret1, _ := ret[1].(int)
        ret2, _ := ret[2].(error)
        return ret0, ret1, ret2
}

// GetAllMessengerRelatedUsers indicates an expected call of GetAllMessengerRelatedUsers.
func (mr *MockMessengerRepositoryMockRecorder) GetAllMessengerRelatedUsers(ctx, page, pageSize, orderBy any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMessengerRelatedUsers", reflect.TypeOf((*MockMessengerRepository)(nil).GetAllMessengerRelatedUsers), ctx, page, pageSize, orderBy)
}

// GetAllMessengers mocks base method.
func (m *MockMessengerRepository) GetAllMessengers(ctx context.Context, page, pageSize int, orderBy string) ([]*models.Messenger, int, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetAllMessengers", ctx, page, pageSize, orderBy)
        ret0, _ := ret[0].([]*models.Messenger)
        ret1, _ := ret[1].(int)
        ret2, _ := ret[2].(error)
        return ret0, ret1, ret2
}

// GetAllMessengers indicates an expected call of GetAllMessengers.
func (mr *MockMessengerRepositoryMockRecorder) GetAllMessengers(ctx, page, pageSize, orderBy any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMessengers", reflect.TypeOf((*MockMessengerRepository)(nil).GetAllMessengers), ctx, page, pageSize, orderBy)
}

// GetMessengerByID mocks base method.
func (m *MockMessengerRepository) GetMessengerByID(ctx context.Context, id int64) (*models.Messenger, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetMessengerByID", ctx, id)
        ret0, _ := ret[0].(*models.Messenger)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetMessengerByID indicates an expected call of GetMessengerByID.
func (mr *MockMessengerRepositoryMockRecorder) GetMessengerByID(ctx, id any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessengerByID", reflect.TypeOf((*MockMessengerRepository)(nil).GetMessengerByID), ctx, id)
}

// GetMessengerIDByName mocks base method.
func (m *MockMessengerRepository) GetMessengerIDByName(ctx context.Context, messengerName string) (int64, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetMessengerIDByName", ctx, messengerName)
        ret0, _ := ret[0].(int64)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetMessengerIDByName indicates an expected call of GetMessengerIDByName.
func (mr *MockMessengerRepositoryMockRecorder) GetMessengerIDByName(ctx, messengerName any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessengerIDByName", reflect.TypeOf((*MockMessengerRepository)(nil).GetMessengerIDByName), ctx, messengerName)
}

// GetMessengerRelatedUser mocks base method.
func (m *MockMessengerRepository) GetMessengerRelatedUser(ctx context.Context, chatID, messengerUserID string, userID, messengerID *int64) (*models.MessengerRelatedUser, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetMessengerRelatedUser", ctx, chatID, messengerUserID, userID, messengerID)
        ret0, _ := ret[0].(*models.MessengerRelatedUser)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetMessengerRelatedUser indicates an expected call of GetMessengerRelatedUser.
func (mr *MockMessengerRepositoryMockRecorder) GetMessengerRelatedUser(ctx, chatID, messengerUserID, userID, messengerID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessengerRelatedUser", reflect.TypeOf((*MockMessengerRepository)(nil).GetMessengerRelatedUser), ctx, chatID, messengerUserID, userID, messengerID)
}

// GetMessengerRelatedUserByID mocks base method.
func (m *MockMessengerRepository) GetMessengerRelatedUserByID(ctx context.Context, messengerUserID int) (*models.MessengerRelatedUser, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetMessengerRelatedUserByID", ctx, messengerUserID)
        ret0, _ := ret[0].(*models.MessengerRelatedUser)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetMessengerRelatedUserByID indicates an expected call of GetMessengerRelatedUserByID.
func (mr *MockMessengerRepositoryMockRecorder) GetMessengerRelatedUserByID(ctx, messengerUserID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessengerRelatedUserByID", reflect.TypeOf((*MockMessengerRepository)(nil).GetMessengerRelatedUserByID), ctx, messengerUserID)
}

// GetUserID mocks base method.
func (m *MockMessengerRepository) GetUserID(ctx context.Context, messengerUserID string) (int64, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetUserID", ctx, messengerUserID)
        ret0, _ := ret[0].(int64)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetUserID indicates an expected call of GetUserID.
func (mr *MockMessengerRepositoryMockRecorder) GetUserID(ctx, messengerUserID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserID", reflect.TypeOf((*MockMessengerRepository)(nil).GetUserID), ctx, messengerUserID)
}