// Code generated by MockGen. DO NOT EDIT.
// Source: messenger_repository.go
//
// Generated by this command:
//
//      mockgen -source=messenger_repository.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
        reflect "reflect"

        models "github.com/boskuv/goreminder/internal/models"
        gomock "go.uber.org/mock/gomock"
)

// MockMessengerRepository is a mock of MessengerRepository interface.
type MockMessengerRepository struct {
        ctrl     *gomock.Controller
        recorder *MockMessengerRepositoryMockRecorder
        isgomock struct{}
}

// MockMessengerRepositoryMockRecorder is the mock recorder for MockMessengerRepository.
type MockMessengerRepositoryMockRecorder struct {
        mock *MockMessengerRepository
}

// NewMockMessengerRepository creates a new mock instance.
func NewMockMessengerRepository(ctrl *gomock.Controller) *MockMessengerRepository {
        mock := &MockMessengerRepository{ctrl: ctrl}
        mock.recorder = &MockMessengerRepositoryMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessengerRepository) EXPECT() *MockMessengerRepositoryMockRecorder {
        return m.recorder
}

// CreateMessenger mocks base method.
func (m *MockMessengerRepository) CreateMessenger(messenger *models.Messenger) (int64, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "CreateMessenger", messenger)
        ret0, _ := ret[0].(int64)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// CreateMessenger indicates an expected call of CreateMessenger.
func (mr *MockMessengerRepositoryMockRecorder) CreateMessenger(messenger any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessenger", reflect.TypeOf((*MockMessengerRepository)(nil).CreateMessenger), messenger)
}

// CreateMessengerRelatedUser mocks base method.
func (m *MockMessengerRepository) CreateMessengerRelatedUser(messengerRelatedUser *models.MessengerRelatedUser) (int64, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "CreateMessengerRelatedUser", messengerRelatedUser)
        ret0, _ := ret[0].(int64)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// CreateMessengerRelatedUser indicates an expected call of CreateMessengerRelatedUser.
func (mr *MockMessengerRepositoryMockRecorder) CreateMessengerRelatedUser(messengerRelatedUser any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessengerRelatedUser", reflect.TypeOf((*MockMessengerRepository)(nil).CreateMessengerRelatedUser), messengerRelatedUser)
}

// GetMessengerByID mocks base method.
func (m *MockMessengerRepository) GetMessengerByID(id int64) (*models.Messenger, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetMessengerByID", id)
        ret0, _ := ret[0].(*models.Messenger)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetMessengerByID indicates an expected call of GetMessengerByID.
func (mr *MockMessengerRepositoryMockRecorder) GetMessengerByID(id any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessengerByID", reflect.TypeOf((*MockMessengerRepository)(nil).GetMessengerByID), id)
}

// GetMessengerIDByName mocks base method.
func (m *MockMessengerRepository) GetMessengerIDByName(messengerName string) (int64, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetMessengerIDByName", messengerName)
        ret0, _ := ret[0].(int64)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetMessengerIDByName indicates an expected call of GetMessengerIDByName.
func (mr *MockMessengerRepositoryMockRecorder) GetMessengerIDByName(messengerName any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessengerIDByName", reflect.TypeOf((*MockMessengerRepository)(nil).GetMessengerIDByName), messengerName)
}

// GetMessengerRelatedUser mocks base method.
func (m *MockMessengerRepository) GetMessengerRelatedUser(chatID, messengerUserID string, userID, messengerID *int64) (*models.MessengerRelatedUser, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetMessengerRelatedUser", chatID, messengerUserID, userID, messengerID)
        ret0, _ := ret[0].(*models.MessengerRelatedUser)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetMessengerRelatedUser indicates an expected call of GetMessengerRelatedUser.
func (mr *MockMessengerRepositoryMockRecorder) GetMessengerRelatedUser(chatID, messengerUserID, userID, messengerID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessengerRelatedUser", reflect.TypeOf((*MockMessengerRepository)(nil).GetMessengerRelatedUser), chatID, messengerUserID, userID, messengerID)
}

// GetMessengerRelatedUserByID mocks base method.
func (m *MockMessengerRepository) GetMessengerRelatedUserByID(messengerUserID int) (*models.MessengerRelatedUser, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetMessengerRelatedUserByID", messengerUserID)
        ret0, _ := ret[0].(*models.MessengerRelatedUser)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetMessengerRelatedUserByID indicates an expected call of GetMessengerRelatedUserByID.
func (mr *MockMessengerRepositoryMockRecorder) GetMessengerRelatedUserByID(messengerUserID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessengerRelatedUserByID", reflect.TypeOf((*MockMessengerRepository)(nil).GetMessengerRelatedUserByID), messengerUserID)
}

// GetUserID mocks base method.
func (m *MockMessengerRepository) GetUserID(messengerUserID string) (int64, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetUserID", messengerUserID)
        ret0, _ := ret[0].(int64)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetUserID indicates an expected call of GetUserID.
func (mr *MockMessengerRepositoryMockRecorder) GetUserID(messengerUserID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserID", reflect.TypeOf((*MockMessengerRepository)(nil).GetUserID), messengerUserID)
}