// Code generated by MockGen. DO NOT EDIT.
// Source: target_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	models "github.com/boskuv/goreminder/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockTargetRepository is a mock of TargetRepository interface.
type MockTargetRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTargetRepositoryMockRecorder
}

// MockTargetRepositoryMockRecorder is the mock recorder for MockTargetRepository.
type MockTargetRepositoryMockRecorder struct {
	mock *MockTargetRepository
}

// NewMockTargetRepository creates a new mock instance.
func NewMockTargetRepository(ctrl *gomock.Controller) *MockTargetRepository {
	mock := &MockTargetRepository{ctrl: ctrl}
	mock.recorder = &MockTargetRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTargetRepository) EXPECT() *MockTargetRepositoryMockRecorder {
	return m.recorder
}

// CreateTarget mocks base method.
func (m *MockTargetRepository) CreateTarget(ctx context.Context, target *models.Target) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTarget", ctx, target)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTarget indicates an expected call of CreateTarget.
func (mr *MockTargetRepositoryMockRecorder) CreateTarget(ctx, target interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTarget", reflect.TypeOf((*MockTargetRepository)(nil).CreateTarget), ctx, target)
}

// DeleteTarget mocks base method.
func (m *MockTargetRepository) DeleteTarget(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTarget", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTarget indicates an expected call of DeleteTarget.
func (mr *MockTargetRepositoryMockRecorder) DeleteTarget(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTarget", reflect.TypeOf((*MockTargetRepository)(nil).DeleteTarget), ctx, id)
}

// GetAllTargets mocks base method.
func (m *MockTargetRepository) GetAllTargets(ctx context.Context, page, pageSize int, orderBy string, userID *int64) ([]*models.Target, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTargets", ctx, page, pageSize, orderBy, userID)
	ret0, _ := ret[0].([]*models.Target)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllTargets indicates an expected call of GetAllTargets.
func (mr *MockTargetRepositoryMockRecorder) GetAllTargets(ctx, page, pageSize, orderBy, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTargets", reflect.TypeOf((*MockTargetRepository)(nil).GetAllTargets), ctx, page, pageSize, orderBy, userID)
}

// GetTargetByID mocks base method.
func (m *MockTargetRepository) GetTargetByID(ctx context.Context, id int64) (*models.Target, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTargetByID", ctx, id)
	ret0, _ := ret[0].(*models.Target)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTargetByID indicates an expected call of GetTargetByID.
func (mr *MockTargetRepositoryMockRecorder) GetTargetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTargetByID", reflect.TypeOf((*MockTargetRepository)(nil).GetTargetByID), ctx, id)
}

// UpdateTarget mocks base method.
func (m *MockTargetRepository) UpdateTarget(ctx context.Context, target *models.Target) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTarget", ctx, target)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTarget indicates an expected call of UpdateTarget.
func (mr *MockTargetRepositoryMockRecorder) UpdateTarget(ctx, target interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTarget", reflect.TypeOf((*MockTargetRepository)(nil).UpdateTarget), ctx, target)
}
