// Code generated by MockGen. DO NOT EDIT.
// Source: task_repository.go
//
// Generated by this command:
//
//      mockgen -source=task_repository.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
        context "context"
        reflect "reflect"
        time "time"

        models "github.com/boskuv/goreminder/internal/models"
        sqlx "github.com/jmoiron/sqlx"
        gomock "go.uber.org/mock/gomock"
)

// MockTaskRepository is a mock of TaskRepository interface.
type MockTaskRepository struct {
        ctrl     *gomock.Controller
        recorder *MockTaskRepositoryMockRecorder
        isgomock struct{}
}

// MockTaskRepositoryMockRecorder is the mock recorder for MockTaskRepository.
type MockTaskRepositoryMockRecorder struct {
        mock *MockTaskRepository
}

// NewMockTaskRepository creates a new mock instance.
func NewMockTaskRepository(ctrl *gomock.Controller) *MockTaskRepository {
        mock := &MockTaskRepository{ctrl: ctrl}
        mock.recorder = &MockTaskRepositoryMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepository) EXPECT() *MockTaskRepositoryMockRecorder {
        return m.recorder
}

// CreateTask mocks base method.
func (m *MockTaskRepository) CreateTask(ctx context.Context, task *models.Task) (int64, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "CreateTask", ctx, task)
        ret0, _ := ret[0].(int64)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTaskRepositoryMockRecorder) CreateTask(ctx, task any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTaskRepository)(nil).CreateTask), ctx, task)
}

// DeleteChildTasks mocks base method.
func (m *MockTaskRepository) DeleteChildTasks(ctx context.Context, parentID int64) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "DeleteChildTasks", ctx, parentID)
        ret0, _ := ret[0].(error)
        return ret0
}

// DeleteChildTasks indicates an expected call of DeleteChildTasks.
func (mr *MockTaskRepositoryMockRecorder) DeleteChildTasks(ctx, parentID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChildTasks", reflect.TypeOf((*MockTaskRepository)(nil).DeleteChildTasks), ctx, parentID)
}

// DeleteChildTasksWithTx mocks base method.
func (m *MockTaskRepository) DeleteChildTasksWithTx(ctx context.Context, tx *sqlx.Tx, parentID int64) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "DeleteChildTasksWithTx", ctx, tx, parentID)
        ret0, _ := ret[0].(error)
        return ret0
}

// DeleteChildTasksWithTx indicates an expected call of DeleteChildTasksWithTx.
func (mr *MockTaskRepositoryMockRecorder) DeleteChildTasksWithTx(ctx, tx, parentID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChildTasksWithTx", reflect.TypeOf((*MockTaskRepository)(nil).DeleteChildTasksWithTx), ctx, tx, parentID)
}

// DeleteTask mocks base method.
func (m *MockTaskRepository) DeleteTask(ctx context.Context, id int64) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "DeleteTask", ctx, id)
        ret0, _ := ret[0].(error)
        return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockTaskRepositoryMockRecorder) DeleteTask(ctx, id any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockTaskRepository)(nil).DeleteTask), ctx, id)
}

// DeleteTaskWithTx mocks base method.
func (m *MockTaskRepository) DeleteTaskWithTx(ctx context.Context, tx *sqlx.Tx, id int64) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "DeleteTaskWithTx", ctx, tx, id)
        ret0, _ := ret[0].(error)
        return ret0
}

// DeleteTaskWithTx indicates an expected call of DeleteTaskWithTx.
func (mr *MockTaskRepositoryMockRecorder) DeleteTaskWithTx(ctx, tx, id any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTaskWithTx", reflect.TypeOf((*MockTaskRepository)(nil).DeleteTaskWithTx), ctx, tx, id)
}

// GetAllTasks mocks base method.
func (m *MockTaskRepository) GetAllTasks(ctx context.Context, page, pageSize int, orderBy string, status *string, startDateFrom, startDateTo *time.Time, userID *int64) ([]*models.Task, int, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetAllTasks", ctx, page, pageSize, orderBy, status, startDateFrom, startDateTo, userID)
        ret0, _ := ret[0].([]*models.Task)
        ret1, _ := ret[1].(int)
        ret2, _ := ret[2].(error)
        return ret0, ret1, ret2
}

// GetAllTasks indicates an expected call of GetAllTasks.
func (mr *MockTaskRepositoryMockRecorder) GetAllTasks(ctx, page, pageSize, orderBy, status, startDateFrom, startDateTo, userID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTasks", reflect.TypeOf((*MockTaskRepository)(nil).GetAllTasks), ctx, page, pageSize, orderBy, status, startDateFrom, startDateTo, userID)
}

// GetChildTasksByParentID mocks base method.
func (m *MockTaskRepository) GetChildTasksByParentID(ctx context.Context, parentID int64) ([]*models.Task, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetChildTasksByParentID", ctx, parentID)
        ret0, _ := ret[0].([]*models.Task)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetChildTasksByParentID indicates an expected call of GetChildTasksByParentID.
func (mr *MockTaskRepositoryMockRecorder) GetChildTasksByParentID(ctx, parentID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChildTasksByParentID", reflect.TypeOf((*MockTaskRepository)(nil).GetChildTasksByParentID), ctx, parentID)
}

// GetDB mocks base method.
func (m *MockTaskRepository) GetDB() *sqlx.DB {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetDB")
        ret0, _ := ret[0].(*sqlx.DB)
        return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockTaskRepositoryMockRecorder) GetDB() *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockTaskRepository)(nil).GetDB))
}

// GetTaskByID mocks base method.
func (m *MockTaskRepository) GetTaskByID(ctx context.Context, id int64) (*models.Task, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetTaskByID", ctx, id)
        ret0, _ := ret[0].(*models.Task)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetTaskByID indicates an expected call of GetTaskByID.
func (mr *MockTaskRepositoryMockRecorder) GetTaskByID(ctx, id any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByID", reflect.TypeOf((*MockTaskRepository)(nil).GetTaskByID), ctx, id)
}

// GetTaskByIDWithoutStatusFilter mocks base method.
func (m *MockTaskRepository) GetTaskByIDWithoutStatusFilter(ctx context.Context, id int64) (*models.Task, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetTaskByIDWithoutStatusFilter", ctx, id)
        ret0, _ := ret[0].(*models.Task)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetTaskByIDWithoutStatusFilter indicates an expected call of GetTaskByIDWithoutStatusFilter.
func (mr *MockTaskRepositoryMockRecorder) GetTaskByIDWithoutStatusFilter(ctx, id any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByIDWithoutStatusFilter", reflect.TypeOf((*MockTaskRepository)(nil).GetTaskByIDWithoutStatusFilter), ctx, id)
}

// GetTasksByUserID mocks base method.
func (m *MockTaskRepository) GetTasksByUserID(ctx context.Context, userID int64) ([]*models.Task, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetTasksByUserID", ctx, userID)
        ret0, _ := ret[0].([]*models.Task)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetTasksByUserID indicates an expected call of GetTasksByUserID.
func (mr *MockTaskRepositoryMockRecorder) GetTasksByUserID(ctx, userID any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByUserID", reflect.TypeOf((*MockTaskRepository)(nil).GetTasksByUserID), ctx, userID)
}

// GetTasksByUserIDWithPagination mocks base method.
func (m *MockTaskRepository) GetTasksByUserIDWithPagination(ctx context.Context, userID int64, page, pageSize int, orderBy string, startDateFrom, startDateTo, createdAtFrom, createdAtTo *time.Time, requiresConfirmation *bool) ([]*models.Task, int, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetTasksByUserIDWithPagination", ctx, userID, page, pageSize, orderBy, startDateFrom, startDateTo, createdAtFrom, createdAtTo, requiresConfirmation)
        ret0, _ := ret[0].([]*models.Task)
        ret1, _ := ret[1].(int)
        ret2, _ := ret[2].(error)
        return ret0, ret1, ret2
}

// GetTasksByUserIDWithPagination indicates an expected call of GetTasksByUserIDWithPagination.
func (mr *MockTaskRepositoryMockRecorder) GetTasksByUserIDWithPagination(ctx, userID, page, pageSize, orderBy, startDateFrom, startDateTo, createdAtFrom, createdAtTo, requiresConfirmation any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByUserIDWithPagination", reflect.TypeOf((*MockTaskRepository)(nil).GetTasksByUserIDWithPagination), ctx, userID, page, pageSize, orderBy, startDateFrom, startDateTo, createdAtFrom, createdAtTo, requiresConfirmation)
}

// GetTasksNeedingRescheduling mocks base method.
func (m *MockTaskRepository) GetTasksNeedingRescheduling(ctx context.Context) ([]*models.Task, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetTasksNeedingRescheduling", ctx)
        ret0, _ := ret[0].([]*models.Task)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetTasksNeedingRescheduling indicates an expected call of GetTasksNeedingRescheduling.
func (mr *MockTaskRepositoryMockRecorder) GetTasksNeedingRescheduling(ctx any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksNeedingRescheduling", reflect.TypeOf((*MockTaskRepository)(nil).GetTasksNeedingRescheduling), ctx)
}

// GetTasksWithCronNeedingRescheduling mocks base method.
func (m *MockTaskRepository) GetTasksWithCronNeedingRescheduling(ctx context.Context) ([]*models.Task, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetTasksWithCronNeedingRescheduling", ctx)
        ret0, _ := ret[0].([]*models.Task)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetTasksWithCronNeedingRescheduling indicates an expected call of GetTasksWithCronNeedingRescheduling.
func (mr *MockTaskRepositoryMockRecorder) GetTasksWithCronNeedingRescheduling(ctx any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksWithCronNeedingRescheduling", reflect.TypeOf((*MockTaskRepository)(nil).GetTasksWithCronNeedingRescheduling), ctx)
}

// UpdateTask mocks base method.
func (m *MockTaskRepository) UpdateTask(ctx context.Context, task *models.Task) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "UpdateTask", ctx, task)
        ret0, _ := ret[0].(error)
        return ret0
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockTaskRepositoryMockRecorder) UpdateTask(ctx, task any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockTaskRepository)(nil).UpdateTask), ctx, task)
}

// UpdateTaskWithTx mocks base method.
func (m *MockTaskRepository) UpdateTaskWithTx(ctx context.Context, tx *sqlx.Tx, task *models.Task) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "UpdateTaskWithTx", ctx, tx, task)
        ret0, _ := ret[0].(error)
        return ret0
}

// UpdateTaskWithTx indicates an expected call of UpdateTaskWithTx.
func (mr *MockTaskRepositoryMockRecorder) UpdateTaskWithTx(ctx, tx, task any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskWithTx", reflect.TypeOf((*MockTaskRepository)(nil).UpdateTaskWithTx), ctx, tx, task)
}