// Code generated by MockGen. DO NOT EDIT.
// Source: task_history_repository.go
//
// Generated by this command:
//
//      mockgen -source=task_history_repository.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	models "github.com/boskuv/goreminder/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskHistoryRepository is a mock of TaskHistoryRepository interface.
type MockTaskHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskHistoryRepositoryMockRecorder
}

// MockTaskHistoryRepositoryMockRecorder is the mock recorder for MockTaskHistoryRepository.
type MockTaskHistoryRepositoryMockRecorder struct {
	mock *MockTaskHistoryRepository
}

// NewMockTaskHistoryRepository creates a new mock instance.
func NewMockTaskHistoryRepository(ctrl *gomock.Controller) *MockTaskHistoryRepository {
	mock := &MockTaskHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockTaskHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskHistoryRepository) EXPECT() *MockTaskHistoryRepositoryMockRecorder {
	return m.recorder
}

// CreateTaskHistory mocks base method.
func (m *MockTaskHistoryRepository) CreateTaskHistory(ctx context.Context, history *models.TaskHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTaskHistory", ctx, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTaskHistory indicates an expected call of CreateTaskHistory.
func (mr *MockTaskHistoryRepositoryMockRecorder) CreateTaskHistory(ctx, history interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTaskHistory", reflect.TypeOf((*MockTaskHistoryRepository)(nil).CreateTaskHistory), ctx, history)
}

// GetTaskHistoryByTaskID mocks base method.
func (m *MockTaskHistoryRepository) GetTaskHistoryByTaskID(ctx context.Context, taskID int64) ([]*models.TaskHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskHistoryByTaskID", ctx, taskID)
	ret0, _ := ret[0].([]*models.TaskHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskHistoryByTaskID indicates an expected call of GetTaskHistoryByTaskID.
func (mr *MockTaskHistoryRepositoryMockRecorder) GetTaskHistoryByTaskID(ctx, taskID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskHistoryByTaskID", reflect.TypeOf((*MockTaskHistoryRepository)(nil).GetTaskHistoryByTaskID), ctx, taskID)
}

// GetTaskHistoryByUserID mocks base method.
func (m *MockTaskHistoryRepository) GetTaskHistoryByUserID(ctx context.Context, userID int64, limit, offset int) ([]*models.TaskHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskHistoryByUserID", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]*models.TaskHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskHistoryByUserID indicates an expected call of GetTaskHistoryByUserID.
func (mr *MockTaskHistoryRepositoryMockRecorder) GetTaskHistoryByUserID(ctx, userID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskHistoryByUserID", reflect.TypeOf((*MockTaskHistoryRepository)(nil).GetTaskHistoryByUserID), ctx, userID, limit, offset)
}

